In [28]:
import numpy as np
import pandas as pd

# A)

Displaying the singular values for matrix $A$

In [29]:
A = np.array([[6, 5, 3],
              [4, 1, 5],
              [6, 3, 6],
              [5, 3, 6],
              [6, 6, 3]])

u, s, v = np.linalg.svd(A)

s

array([17.92667464,  4.69961929,  0.74021274])

# B)
Finding the eigenvalues of $A$.

In [30]:
# a_square = np.matmul(A.T, A)
a_square = A.T @ A
a_square

array([[149, 103, 122],
       [103,  80,  74],
       [122,  74, 115]])

In [31]:
eigenvalues, eigenvectors = np.linalg.eig(a_square)
eigenvalues

array([321.36566366,   0.54791491,  22.08642144])

The singular value $ \sigma _i $ are related to the eigenvalue $ \lambda _i$ by:

$$
\sigma _i = \sqrt{\lambda _i}
$$


# C)
Because there are only 3 singular values in A), $ rank(A) = 3 $

In [47]:
np.linalg.matrix_rank(A)

3

# D)
Yes, even though the column space and row space do not have the same dimensionality, m > n and each column vector is linearly independent. This means that our input space is $\mathbb{R^3}$ and maps onto $\mathbb{R^5}$ - however they do not span all of $\mathbb{R^5}$. The three column vectors are linearly independent meaning $Span({v_1, v_2, v_3}) = 3$, where $v_i$ is a column vector in $A$. Because the $Span({v_1, v_2, v_3}) = dim(Col(A))$, if there is a solution, then the solution is unique.

# E)
Finding solution or approximation for $$ b = \begin{bmatrix} -1\\2\\0\\3\\1 \end{bmatrix} $$



In [44]:
# b = np.array([-1,2,0,3,1])
b = np.array([6, 0 ,0 , 0 ,0 ])
b

array([6, 0, 0, 0, 0])

In [33]:
A

array([[6, 5, 3],
       [4, 1, 5],
       [6, 3, 6],
       [5, 3, 6],
       [6, 6, 3]])

In [45]:
# testing on b
b = A.T[0]
b

array([6, 4, 6, 5, 6])

In [46]:
np.linalg.solve(A, b)

LinAlgError: Last 2 dimensions of the array must be square

In [38]:
x,_ ,_,_ =np.linalg.lstsq(A, b, rcond=None)
x

array([-2.06119825,  1.37336076,  1.54641296])