In [23]:
import numpy as np
import pandas as pd

In [24]:
A = np.array([[6, 5, 3],
              [4, 1, 5],
              [6, 3, 6],
              [5, 3, 6],
              [6, 6, 3]])

u, s, v = np.linalg.svd(A)

s

array([17.92667464,  4.69961929,  0.74021274])

In [25]:
a_square = np.matmul(A.T, A)
a_square

array([[149, 103, 122],
       [103,  80,  74],
       [122,  74, 115]])

In [26]:
eigenvalues, eigenvectors = np.linalg.eig(a_square)
eigenvalues

array([321.36566366,   0.54791491,  22.08642144])